chain_width = 80
edition = "2021"
fn_call_width = 80
format_code_in_doc_comments = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
reorder_impl_items = true
struct_lit_width = 35
unstable_features = true
use_field_init_shorthand = true
version = "Two"
